const ResponseMessage = {
  LOGIN: {
    INFO: {
      SUCCESS: 'LOGIN.INFO.SUCCESS',
    },
    ERROR: {
      USER_ID_EMPTY: 'ERROR.LOGIN.USER_ID_EMPTY',
      PASSWORD_EMPTY: 'ERROR.LOGIN.PASSWORD_EMPTY',
      USER_NOT_EXISTS: 'ERROR.LOGIN.USER_NOT_EXISTS',
      PASSWORD_WRONG: 'ERROR.LOGIN_PASSWORD_WRONG',
    },
  },
  REGISTER: {
    INFO: {
      SUCCESS: 'REGISTER.INFO.SUCCESS',
    },
    ERROR: {
      USER_ID_EXISTED: 'ERROR.REGISTER.USER_ID_EXISTED',
      USER_ID_RULE_NOT_MATCH: 'ERROR.REGISTER.USER_ID_RULE_NOT_MATCH',
      PASSWORD_RULE_NOT_MATCH: 'ERROR.REGISTER.PASSWORD_RULE_NOT_MATCH',
    },
  },
};

export default ResponseMessage;
