const ResponseMessage = {
  LOGIN: {
    INFO: {
      SUCCESS: 'LOGIN.INFO.SUCCESS',
    },
    ERROR: {
      USER_ID_EMPTY: 'LOGIN.ERROR.USER_ID_EMPTY',
      PASSWORD_EMPTY: 'LOGIN.ERROR.PASSWORD_EMPTY',
      USER_NOT_EXISTS: 'LOGIN.ERROR.USER_NOT_EXISTS',
      PASSWORD_WRONG: 'LOGIN.ERROR.PASSWORD_WRONG',
    },
  },
  REGISTER: {
    INFO: {
      SUCCESS: 'REGISTER.INFO.SUCCESS',
    },
    ERROR: {
      USER_ID_EXISTED: 'REGISTER.ERROR.USER_ID_EXISTED',
      USER_ID_RULE_NOT_MATCH: 'REGISTER.ERROR.USER_ID_RULE_NOT_MATCH',
      PASSWORD_RULE_NOT_MATCH: 'REGISTER.ERROR.PASSWORD_RULE_NOT_MATCH',
    },
  },
  AUTH: {
    INFO: {
      SUCCESS: 'AUTH.INFO.SUCCESS',
    },
    ERROR: {
      USER_ID_EMPTY: 'AUTH.ERROR.USER_ID_EMPTY',
      SESSION_ID_EMPTY: 'AUTH.ERROR.SESSION_ID_EMPTY',
      USER_NOT_EXIST: 'AUTH.ERROR.USER_NOT_EXIST',
      SESSION_NOT_EXIST: 'AUTH.ERROR.SESSION_NOT_EXIST',
      SESSION_VERIFICATION_FAILED: 'AUTH.ERROR.SESSION_VERIFICATION_FAILED',
    },
  },
  CREATE_TAG: {
    INFO: {
      SUCCESS: 'CREATE_TAG.INFO.SUCCESS',
    },
    ERROR: {
      TAG_ID_EMPTY: 'CREATE_TAG.ERROR.TAG_ID_EMPTY',
      KEY_EMPTY: 'CREATE_TAG.ERROR.KEY_EMPTY',
      WRONG_TAG_ID_FORMAT: 'CREATE_TAG.ERROR.WRONG_TAG_ID_FORMAT',
      KEY_SHOULD_BE_CHINESE: 'CREATE_TAG.ERROR.KEY_SHOULD_BE_CHINESE',
    },
  },
  SUBSCRIBE_TAG: {
    INFO: {
      SUCCESS: 'SUBSCRIBE_TAG.INFO.SUCCESS',
    },
    ERROR: {
      TAG_ID_EMPTY: 'SUBSCRIBE_TAG.ERROR.TAG_ID_EMPTY',
      TAG_NOT_EXIST: 'SUBSCRIBE_TAG.ERROR.TAG_NOT_EXIST',
    },
  },
  CANCEL_SUBSCRIBE_TAG: {
    INFO: {
      SUCCESS: 'CANCEL_SUBSCRIBE_TAG.INFO.SUCCESS',
    },
    ERROR: {
      TAG_ID_EMPTY: 'CANCEL_SUBSCRIBE_TAG.ERROR.TAG_ID_EMPTY',
      TAG_NOT_EXIST: 'CANCEL_SUBSCRIBE_TAG.ERROR.TAG_NOT_EXIST',
    },
  },
  KICK_SUBSCRIBE_TAG: {
    INFO: {
      SUCCESS: 'KICK_SUBSCRIBE_TAG.INFO.SUCCESS',
    },
    ERROR: {
      TAG_ID_EMPTY: 'KICK_SUBSCRIBE_TAG.ERROR.TAG_ID_EMPTY',
      KICK_USER_ID_EMPTY: 'KICK_SUBSCRIBE_TAG.ERROR.KICK_USER_ID_EMPTY',
      KICK_USER_NOT_EXIST: 'KICK_SUBSCRIBE_TAG.ERROR.KICK_USER_NOT_EXIST',
      TAG_NOT_EXIST: 'KICK_SUBSCRIBE_TAG.ERROR.TAG_NOT_EXIST',
      TAG_NOT_YOUR_OWN: 'KICK_SUBSCRIBE_TAG.ERROR.TAG_NOT_YOUR_OWN',
    },
  },
  DELETE_TAG: {
    INFO: {
      SUCCESS: 'DELETE_TAG.INFO.SUCCESS',
    },
    ERROR: {
      TAG_ID_EMPTY: 'DELETE_TAG.ERROR.TAG_ID_EMPTY',
      KICK_USER_ID_EMPTY: 'DELETE_TAG.ERROR.KICK_USER_ID_EMPTY',
      KICK_USER_NOT_EXIST: 'DELETE_TAG.ERROR.KICK_USER_NOT_EXIST',
      TAG_NOT_EXIST: 'DELETE_TAG.ERROR.TAG_NOT_EXIST',
      TAG_NOT_YOUR_OWN: 'DELETE_TAG.ERROR.TAG_NOT_YOUR_OWN',
    },
  },
  UPLOAD_STICKER: {
    INFO: {
      SUCCESS: 'UPLOAD_STICKER.INFO.SUCCESS',
    },
    ERROR: {
      STICKER_ID_EMPTY: 'UPLOAD_STICKER.ERROR.STICKER_ID_EMPTY',
      DESCRIPTION_EMPTY: 'UPLOAD_STICKER.ERROR.DESCRIPTION_EMPTY',
      TYPE_EMPTY: 'UPLOAD_STICKER.ERROR.TYPE_EMPTY',
      FILE_NOT_EXIST: 'UPLOAD_STICKER.ERROR.FILE_NOT_EXIST',
      WRONG_IMAGE_FORMAT: 'UPLOAD_STICKER.ERROR.WRONG_IMAGE_FORMAT',
      WRONG_STICKER_ID_FORMAT: 'CREATE_TAG.ERROR.WRONG_STICKER_ID_FORMAT',
      DESC_SHOULD_BE_CHINESE: 'UPLOAD_STICKER.ERROR.DESC_SHOULD_BE_CHINESE',
    },
  },
  UPDATE_STICKER: {
    INFO: {
      SUCCESS: 'UPDATE_STICKER.INFO.SUCCESS',
    },
    ERROR: {
      STICKER_ID_EMPTY: 'UPDATE_STICKER.ERROR.STICKER_ID_EMPTY',
      STICKER_NOT_EXIST: 'UPDATE_STICKER.ERROR.STICKER_NOT_EXIST',
      STICKER_NOT_YOUR_OWN: 'UPDATE_STICKER.ERROR.STICKER_NOT_YOUR_OWN',
      DESC_SHOULD_BE_CHINESE: 'UPDATE_STICKER.ERROR.DESC_SHOULD_BE_CHINESE',
      SOME_TAGS_NOT_EXIST: 'UPDATE_STICKER.ERROR.SOME_TAGS_NOT_EXIST',
      SOME_TAGS_NOT_SUBSCRIBED: 'UPDATE_STICKER.ERROR.SOME_TAGS_NOT_SUBSCRIBED',
    },
  },
  DELETE_STICKER: {
    INFO: {
      SUCCESS: 'DELETE_STICKER.INFO.SUCCESS',
    },
    ERROR: {
      STICKER_ID_EMPTY: 'DELETE_STICKER.ERROR.STICKER_ID_EMPTY',
      STICKER_NOT_EXIST: 'DELETE_STICKER.ERROR.STICKER_NOT_EXIST',
      STICKER_NOT_YOUR_OWN: 'DELETE_STICKER.ERROR.STICKER_NOT_YOUR_OWN',
    },
  },
};

export default ResponseMessage;
